services:
  postgres:
    image: postgres:18@sha256:1090bc3a8ccfb0b55f78a494d76f8d603434f7e4553543d6e807bc7bd6bbd17f
    ports:
      - '5490:5432'
    environment:
      POSTGRES_USER: hermit
      POSTGRES_PASSWORD: hermit
      POSTGRES_DB: hermit
    volumes:
      - hermit-pgdata:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hermit']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  hermit-pgdata:
